tap "homebrew/bundle"
tap "homebrew/core", "https://github.com/Homebrew/linuxbrew-core.git"
brew "bat"
brew "ctags"
brew "exa"
brew "fd"
brew "fzf"
brew "gcc"
brew "neovim"
brew "ranger"
brew "ripgrep"
brew "tig"
brew "tmux"
brew "vim"
