- name: Configure system
  hosts: localhost
  become: true
  tasks:
    - name: System
      ansible.builtin.import_tasks: tasks/system.yaml

- name: Configure user home directory
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    versions:
      neovim: v0.9.2
  tasks:
    - name: User
      ansible.builtin.import_tasks: tasks/user.yaml
