- name: Configure system
  hosts: localhost
  become: true
  diff: true
  vars:
    versions:
      kubectl: v1.29
  module_defaults:
    ansible.builtin.setup:
      gather_subset: "!hardware"
  tasks:
    - name: System
      ansible.builtin.import_tasks: tasks/system.yaml

- name: Configure user home directory
  hosts: localhost
  become: false
  diff: true
  gather_facts: false
  vars:
    versions:
      neovim: v0.10.0
  module_defaults:
    ansible.builtin.setup:
      gather_subset: "!hardware"
  tasks:
    - name: User
      ansible.builtin.import_tasks: tasks/user.yaml
