- name: awscliv2 | Create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "~/.cache/dotfiles/awscliv2"
    - "~/.cache/dotfiles/downloads"
    - "~/.local/share/aws-cli"

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: awscliv2 | Download installer
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "~/.cache/dotfiles/downloads/"
  register: awscliv2_download

- name: awscliv2 | Extract installer
  ansible.builtin.unarchive:
    src: "{{ awscliv2_download.dest }}"
    dest: "~/.cache/dotfiles/awscliv2"
  register: awscliv2_extract

- name: awscliv2 | Run installer
  ansible.builtin.command:
  args:
    cmd: "{{ awscliv2_extract.dest }}/aws/install -i ~/.local/share/aws-cli -b ~/.local/bin --update"
  when: awscliv2_extract.changed
  register: awscliv2_install

- name: awscliv2 | Show installer output
  ansible.builtin.debug:
    var: awscliv2_install
    verbosity: 2
