- name: awscliv2 | Create temporary directory
  ansible.builtin.tempfile:
    state: directory
  register: awscliv2_temp_dir

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
- name: awscliv2 | Download installer
  ansible.builtin.unarchive:
    src: "https://awscli.amazonaws.com/awscli-exe-linux-{{ ansible_architecture }}.zip"
    dest: "{{ awscliv2_temp_dir.path }}"
    remote_src: true
    creates: "{{ awscliv2_temp_dir.path }}/aws"
    mode: "0755"
  diff: false

- name: awscliv2 | Run installer
  ansible.builtin.command:
  args:
    cmd: "{{ awscliv2_temp_dir.path }}/aws/install"
    creates: /usr/local/bin/aws
  become: true
  register: awscliv2_install

- name: awscliv2 | Show installer output
  ansible.builtin.debug:
    var: awscliv2_install
    verbosity: 2

- name: awscliv2 | Remove temporary directory
  ansible.builtin.file:
    path: "{{ awscliv2_temp_dir.path }}"
    state: absent
  when: awscliv2_temp_dir.path is defined
  diff: false
