- name: GitHub release (deb) {{ user + '/' + repo }}
  block:
    - name: GitHub release (deb) {{ user + '/' + repo }} | Get release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ user }}/{{ repo }}/releases/{{ release | default('latest') }}
        return_content: true
      register: github_release

    - name: GitHub release (deb) {{ user + '/' + repo }} | Find matching asset(s)
      ansible.builtin.set_fact:
        assets: "{{ github_release.json.assets | selectattr('name', 'search', asset_pattern) }}"

    - name: GitHub release (deb) {{ user + '/' + repo }} | Install
      ansible.builtin.apt:
        deb: "{{ assets | map(attribute='browser_download_url') | list | first }}"
