- name: Add Git PPA
  ansible.builtin.apt_repository:
    repo: ppa:git-core/ppa
    state: present

- name: Add Balto Helm signing key
  ansible.builtin.get_url:
    url: https://baltocdn.com/helm/signing.asc
    dest: /etc/apt/keyrings/balto_helm.asc
    mode: "0644"

- name: Add Balto Helm repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/balto_helm.asc] https://baltocdn.com/helm/stable/debian/ all main
    filename: balto_helm

- name: Add HashiCorp signing key
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /etc/apt/keyrings/hashicorp.asc
    mode: "0644"

- name: Add HashiCorp repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/hashicorp.asc] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    filename: hashicorp

- name: Add Kubernetes signing key
  ansible.builtin.get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /etc/apt/keyrings/kubernetes.asc
    mode: "0644"

- name: Add Kubernetes repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/kubernetes.asc] https://pkgs.k8s.io/core:/stable:/v1.25/deb/ /
    filename: kubernetes

- name: Install packages
  ansible.builtin.apt:
    name:
      - build-essential
      - cmake
      - exa
      - git
      - helm
      - jq
      - keychain
      - kubectl
      - libfuse2
      - ripgrep
      - terraform
      - tig
      - tmux
      - unzip
    state: present
    update_cache: true

- name: Install AWS CLI v2
  ansible.builtin.import_tasks: awscliv2.yaml

- name: Install PowerShell/PowerShell
  ansible.builtin.import_tasks: github_release_deb.yaml
  vars:
    user: PowerShell
    repo: PowerShell
    asset_pattern: 'powershell_.*\.deb_amd64.deb'

- name: Install sharkdp/bat
  ansible.builtin.import_tasks: github_release_deb.yaml
  vars:
    user: sharkdp
    repo: bat
    asset_pattern: 'bat_\d+\.\d+\.\d+_amd64.deb'

- name: Install sharkdp/fd
  ansible.builtin.import_tasks: github_release_deb.yaml
  vars:
    user: sharkdp
    repo: fd
    asset_pattern: 'fd_\d+\.\d+\.\d+_amd64.deb'
