- name: Link dotfiles | home
  with_fileglob: "{{ inventory_dir }}/home/.*"
  ansible.builtin.file:
    path: "~/{{ item | basename }}"
    src: "{{ item }}"
    follow: false
    state: link

- name: Link dotfiles | home/.config | find directories
  ansible.builtin.find:
    paths: "{{ inventory_dir }}/home/.config"
    file_type: directory
    recurse: false
  register: dot_config

- name: Link dotfiles | home/.config
  loop: "{{ dot_config.files }}"
  ansible.builtin.file:
    path: "~/.config/{{ item.path | basename }}"
    src: "{{ item.path }}"
    follow: false
    state: link

- name: Link dotfiles | home/.vim
  ansible.builtin.file:
    path: "~/.vim"
    src: "{{ inventory_dir }}/home/.vim"
    follow: false
    state: link

- name: Install junegunn/fzf
  block:
    - name: Install junegunn/fzf | Clone
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.local/share/fzf
        version: 0.42.0
      register: fzf_git
    - name: Install junegunn/fzf | Run install script
      ansible.builtin.command: ~/.local/share/fzf/install --all --no-zsh --no-fish
      changed_when: fzf_git.changed

- name: Install Neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ versions.neovim }}/nvim.appimage"
    dest: ~/.local/bin/nvim.appimage
    mode: "0744"

- name: Install rustup | download installer
  ansible.builtin.uri:
    url: https://sh.rustup.rs
    return_content: true
  register: rustup_installer

- name: Install rustup
  ansible.builtin.command:
    cmd: sh -s -- -y --no-modify-path
    stdin: "{{ rustup_installer.content }}"
  changed_when: false

- name: Install crates | define list
  ansible.builtin.set_fact:
    crates:
      - starship
      - zoxide
    cacheable: true
  register: crates_list

- name: Install crates
  ansible.builtin.command: ~/.cargo/bin/cargo install --locked {{ crates | join(' ') }}
  changed_when: crates_list.changed
