- name: Link dotfiles | home
  with_fileglob: "{{ inventory_dir }}/home/.*"
  ansible.builtin.file:
    path: "~/{{ item | basename }}"
    src: "{{ item }}"
    follow: false
    state: link

- name: Link dotfiles | home/.config
  loop:
    - "{{ inventory_dir }}/home/.config/broot/verbs.hjson"
    - "{{ inventory_dir }}/home/.config/ctags"
    - "{{ inventory_dir }}/home/.config/lsd"
    - "{{ inventory_dir }}/home/.config/nvim"
  ansible.builtin.file:
    path: "~/.config/{{ item | ansible.builtin.relpath(inventory_dir + '/home/.config') }}"
    src: "{{ item }}"
    follow: false
    state: link

- name: Link dotfiles | home/.vim
  ansible.builtin.file:
    path: "~/.vim"
    src: "{{ inventory_dir }}/home/.vim"
    follow: false
    state: link

- name: Install AWS CLI v2
  ansible.builtin.import_tasks: awscliv2.yaml

- name: Install Broot
  ansible.builtin.get_url:
    url: https://dystroy.org/broot/download/x86_64-linux/broot
    dest: ~/.local/bin/broot
    mode: "0744"

- name: Install Broot | bash-completion (br)
  ansible.builtin.get_url:
    url: https://dystroy.org/broot/download/completion/br.bash
    dest: ~/.local/share/bash-completion/completions/br.bash
    mode: "0644"

- name: Install Broot | bash-completion (broot)
  ansible.builtin.get_url:
    url: https://dystroy.org/broot/download/completion/broot.bash
    dest: ~/.local/share/bash-completion/completions/broot.bash
    mode: "0644"

- name: Install dasel
  ansible.builtin.import_tasks: github_release_binary.yaml
  vars:
    user: TomWright
    repo: dasel
    asset_pattern: "dasel_linux_amd64"
    dest: ~/.local/bin/dasel

- name: Install junegunn/fzf
  block:
    - name: Install junegunn/fzf | Clone
      ansible.builtin.git:
        repo: https://github.com/junegunn/fzf.git
        dest: ~/.local/share/fzf
        version: 0.42.0
      register: fzf_git
    - name: Install junegunn/fzf | Run install script
      ansible.builtin.command: ~/.local/share/fzf/install --all --no-zsh --no-fish
      changed_when: fzf_git.changed

- name: Install Neovim
  ansible.builtin.get_url:
    url: "https://github.com/neovim/neovim/releases/download/{{ versions.neovim }}/nvim.appimage"
    dest: ~/.local/bin/nvim.appimage
    mode: "0744"

- name: Install Neovim | symlink
  ansible.builtin.file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    state: link
  loop:
    - { src: ~/.local/bin/nvim.appimage, path: ~/.local/bin/nvim }
    - { src: ~/.local/bin/nvim.appimage, path: ~/.local/bin/vim }

- name: Install rustup | download installer
  ansible.builtin.uri:
    url: https://sh.rustup.rs
    return_content: true
  register: rustup_installer

- name: Install rustup
  ansible.builtin.command:
    cmd: sh -s -- -y --no-modify-path
    stdin: "{{ rustup_installer.content }}"
  changed_when: false

- name: Install crates | define list
  ansible.builtin.set_fact:
    crates:
      - lsd
      - starship
      - zoxide
    cacheable: true
  register: crates_list

- name: Install crates
  ansible.builtin.command: ~/.cargo/bin/cargo install --locked {{ crates | join(' ') }}
  changed_when: crates_list.changed
